fix build

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -115,49 +115,49 @@ jobs:
   #       cat /home/runner/work/orc/orc/build/java/rat.txt
 
   windows:
-  name: "C++ ${{ matrix.simd }} Test on Windows"
-  runs-on: windows-2025
-  strategy:
-    fail-fast: false
-    matrix:
-      simd:
-        - General
-        # - AVX512
-  env:
-    ORC_USER_SIMD_LEVEL: AVX512
-    VCPKG_ROOT: C:/vcpkg
-  steps:
-  - name: Checkout
-    uses: actions/checkout@v4
-  - name: Add msbuild to PATH
-    uses: microsoft/setup-msbuild@v1.1
-    with:
-      msbuild-architecture: x64
-  - name: Install Install dependencies via vcpkg
-    shell: cmd
-    run: |
-      vcpkg install zlib:x64-windows
-      vcpkg install protobuf:x64-windows
-  - name: "Build and Test"
-    shell: bash
-    run: |
-      mkdir build
-      cd build
-      # Use conan package kind to avoid the vcpkg-specific issues
-      cmake .. -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_LIBHDFSPP=OFF -DBUILD_TOOLS=OFF -DBUILD_JAVA=OFF -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DProtobuf_ROOT="$VCPKG_ROOT/installed/x64-windows" -DCMAKE_PREFIX_PATH="$VCPKG_ROOT/installed/x64-windows" -DORC_PACKAGE_KIND=conan
-      cmake --build . --config Debug
-      if [ $? -ne 0 ]; then
-        echo "Build failed"
-        ls -la
-        exit 1
-      fi
-      ctest -C Debug --output-on-failure
-      if [ $? -ne 0 ]; then
-        echo "Tests failed"
-        ls -la
-        cat DartConfiguration.tcl || echo "No DartConfiguration.tcl"
-        exit 1
-      fi
+    name: "C++ ${{ matrix.simd }} Test on Windows"
+    runs-on: windows-2025
+    strategy:
+      fail-fast: false
+      matrix:
+        simd:
+          - General
+          # - AVX512
+    env:
+      ORC_USER_SIMD_LEVEL: AVX512
+      VCPKG_ROOT: C:/vcpkg
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: Add msbuild to PATH
+      uses: microsoft/setup-msbuild@v1.1
+      with:
+        msbuild-architecture: x64
+    - name: Install Install dependencies via vcpkg
+      shell: cmd
+      run: |
+        vcpkg install zlib:x64-windows
+        vcpkg install protobuf:x64-windows
+    - name: "Build and Test"
+      shell: bash
+      run: |
+        mkdir build
+        cd build
+        # Use conan package kind to avoid the vcpkg-specific issues
+        cmake .. -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_LIBHDFSPP=OFF -DBUILD_TOOLS=OFF -DBUILD_JAVA=OFF -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DProtobuf_ROOT="$VCPKG_ROOT/installed/x64-windows" -DCMAKE_PREFIX_PATH="$VCPKG_ROOT/installed/x64-windows" -DORC_PACKAGE_KIND=conan
+        cmake --build . --config Debug
+        if [ $? -ne 0 ]; then
+          echo "Build failed"
+          ls -la
+          exit 1
+        fi
+        ctest -C Debug --output-on-failure
+        if [ $? -ne 0 ]; then
+          echo "Tests failed"
+          ls -la
+          cat DartConfiguration.tcl || echo "No DartConfiguration.tcl"
+          exit 1
+        fi
     # - name: "Upload Build Artifacts"
     #   if: always()
     #   uses: actions/upload-artifact@v4
